version: "3.8"

services:
  db:
    image: postgres:16
    container_name: pg_container
    restart: always
    environment:
      POSTGRES_DB: Amak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anhthang123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
