version: "3.8"
services:
  api:
    container_name: amak_be
    image: vanthang24803/amak-api-prod:latest
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://*:8080
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - amak

  redis:
    image: redis:latest
    container_name: amak_prod_redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - amak

  rabbitmq:
    image: rabbitmq:latest
    container_name: amak_prod_rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - amak
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  nginx:
    image: nginx:alpine
    container_name: amak_be_nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - amak_be
    networks:
      - amak

networks:
  amak:
    driver: bridge

volumes:
  redis-data:
