version: "3.8"
services:
  api:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - amak

  db:
    image: postgres:latest
    container_name: amak_db
    environment:
      - POSTGRES_DB=Amak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - amak_db:/var/lib/postgresql/data
    networks:
      - amak

  redis:
    image: redis:latest
    container_name: amak_redis
    volumes:
      - amak_redis:/data
    ports:
      - "6379:6379"
    networks:
      - amak

  rabbitmq:
    image: rabbitmq:latest
    container_name: amak_rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - amak_rabbit:/var/lib/rabbitmq
    networks:
      - amak

networks:
  amak:
    driver: bridge

volumes:
  amak_db:
  amak_redis:
  amak_rabbit:
