version: "3.8"

services:
  api:
    build:
      context: ../
      dockerfile: Dockerfile
    image: amak_api
    container_name: amak_be
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - amak
    environment:
      - ASPNETCORE_URLS=http://*:8080
      - ASPNETCORE_ENVIRONMENT=Production

  redis:
    image: redis:latest
    container_name: amak_redis
    ports:
      - "6379:6379"
    volumes:
      - amak_redis:/data
    networks:
      - amak

  rabbitmq:
    image: rabbitmq:latest
    container_name: amak_rabbit
    ports:
      - "5672:5672"
    volumes:
      - amak_rabbit:/var/lib/rabbitmq
    networks:
      - amak
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

networks:
  amak:
    driver: bridge
volumes:
  amak_redis:
  amak_rabbit:
