version: "3.8"
services:
  api:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - pgadmin
    networks:
      - amak

  redis:
    image: redis:latest
    container_name: amak_redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - amak

  pgadmin:
    image: dpage/pgadmin4
    container_name: amak_pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    depends_on:
      - db
    networks:
      - amak

networks:
  amak:
    driver: bridge

volumes:
  redis-data:
